services:
  appDatabase:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: group3
      MYSQL_DATABASE: capstone
    ports: 
      - 3306:3306
    volumes:
      - 'mysql_data:/bitnami/mysql/data'

    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-pgroup3", "-e", "show schemas"]
      interval: 10s

volumes:
  mysql_data:
    driver: local