services:
  appDatabase:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: eplanner
    ports: 
      - 3306:3306
    volumes:
      - 'mysql_data:/bitnami/mysql/data'

    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
      interval: 10s
  app:
    build: .
    restart: always
    environment:
      HTTP_PORT: 3000
      STORAGE: db
    ports:
      - 80:3000

volumes:
  mysql_data:
    driver: local